import 'package:flutter/material.dart';
const prefixWeatherIconUrl = 'https://openweathermap.org/img/wn/';
const suffixWeatherIconUrl = '@2x.png';
const weatherApiKey = 'a3605ed954b18b2bcf19b3fa3be6b571';
const degree = '\u00B0';
const celsius = 'C';
const fahrenheit = 'F';
const String metric = 'metric';
const String imperial = 'imperial';
const cities = ['Athens', 'Berlin', 'Cairo', 'Chittagong', 'Dhaka', 'Jakarta', 'London', 'Los Angeles', 'Moscow', 'New York', 'Sydney', 'Sylhet', 'Tokyo'];
final backgroundColor = Colors.blue.shade900;